

version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - '${PORT}:3306'
    volumes:
      - ./lib/init_db_script.sql:/docker-entrypoint-initdb.d/init_db_script.sql  # 挂载init_db_script.sql文件到容器内的初始化目录
      - ./db_data:/var/lib/mysql  # 持久化MySQL数据
    command: --default-authentication-plugin=mysql_native_password


  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 5555:4444
      - 7900:7900
    shm_size: 1g
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
  # 登录生成Cookie的服务
  gen_cookie:
    build:
      context: .
      dockerfile: Dockerfile.GenCookie
    volumes:
      - .:/app
    restart: always
    depends_on:
      - selenium
#      - db
  # 筛选用户的服务
  search_user:
    build:
      context: .
      dockerfile: Dockerfile.SearchUser
    volumes:
      - .:/app
    restart: always
    depends_on:
      - selenium
#      - db
  # 执行转发动态的服务
  dynamic_share:
    build:
      context: .
      dockerfile: Dockerfile.DynamicShare
    volumes:
      - .:/app
    restart: always
    depends_on:
      - selenium
#      - db



